//! Reference heuristic costs for the lost-sales benchmark grid.
//!
//! Per-instance optimal / Myopic-1 / Myopic-2 / SVBS / capped-base-stock costs.
//! Literature values (Xin 2020 extension of Zipkin 2008) are used where the
//! literature reports them; the remaining cells (Geometric M1/SVBS, Poisson
//! L=10 M1/SVBS, and all Markov-modulated rows) are repo-computed by the
//! `heuristics` evaluator in this crate (IID demand directly; MMPP2 via the
//! stationary-marginal demand law). Each instance records which in `source`.
//!
//! Generated by scripts/lost_sales/generate_rust_reference_costs.py from the
//! recovered literature table and outputs/computed_lost_sales_heuristics_6178f5d.jsonl.

use crate::problems::lost_sales::demand::{LostSalesDemandConfig, LostSalesDemandKind};

/// Reference heuristic mean costs for one lost-sales instance. `None` means the
/// value is neither in the literature nor computed for this instance.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct HeuristicReferenceCosts {
    pub optimal: Option<f64>,
    pub myopic1: Option<f64>,
    pub myopic2: Option<f64>,
    pub svbs: Option<f64>,
    pub capped_base_stock: Option<f64>,
}

/// A benchmark-grid instance with its demand process and reference costs.
#[derive(Clone, Copy)]
pub struct LostSalesReferenceInstance {
    pub name: &'static str,
    pub demand: LostSalesDemandConfig,
    pub lead_time: usize,
    pub holding_cost: f64,
    pub shortage_cost: f64,
    pub costs: HeuristicReferenceCosts,
    /// "literature" | "literature+computed" | "computed".
    pub source: &'static str,
}

/// The full benchmark grid: canonical vanilla instance plus
/// {Poisson, Geometric, MMPP2+, MMPP2-} x p in {4,19} x L in {4,6,8,10}.
pub const REFERENCE_INSTANCES: &[LostSalesReferenceInstance] = &[
    LostSalesReferenceInstance {
        name: "vanilla_l4_p4_poisson5",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::Poisson,
            demand_rate: 5.0,
            demand_lambda_low: 0.0,
            demand_lambda_high: 0.0,
            demand_p00: 0.0,
            demand_p11: 0.0,
        },
        lead_time: 4,
        holding_cost: 1.0,
        shortage_cost: 4.0,
        costs: HeuristicReferenceCosts {
            optimal: Some(4.73),
            myopic1: Some(5.06),
            myopic2: Some(4.82),
            svbs: Some(5.83),
            capped_base_stock: Some(4.8),
        },
        source: "literature",
    },
    LostSalesReferenceInstance {
        name: "lit_poisson_p4_l4",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::Poisson,
            demand_rate: 5.0,
            demand_lambda_low: 0.0,
            demand_lambda_high: 0.0,
            demand_p00: 0.0,
            demand_p11: 0.0,
        },
        lead_time: 4,
        holding_cost: 1.0,
        shortage_cost: 4.0,
        costs: HeuristicReferenceCosts {
            optimal: Some(4.73),
            myopic1: Some(5.06),
            myopic2: Some(4.82),
            svbs: Some(5.83),
            capped_base_stock: Some(4.8),
        },
        source: "literature",
    },
    LostSalesReferenceInstance {
        name: "lit_poisson_p4_l6",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::Poisson,
            demand_rate: 5.0,
            demand_lambda_low: 0.0,
            demand_lambda_high: 0.0,
            demand_p00: 0.0,
            demand_p11: 0.0,
        },
        lead_time: 6,
        holding_cost: 1.0,
        shortage_cost: 4.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(5.4140775),
            myopic2: Some(5.04476375),
            svbs: Some(6.77253875),
            capped_base_stock: Some(5.03894625),
        },
        source: "literature",
    },
    LostSalesReferenceInstance {
        name: "lit_poisson_p4_l8",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::Poisson,
            demand_rate: 5.0,
            demand_lambda_low: 0.0,
            demand_lambda_high: 0.0,
            demand_p00: 0.0,
            demand_p11: 0.0,
        },
        lead_time: 8,
        holding_cost: 1.0,
        shortage_cost: 4.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(5.6982775),
            myopic2: Some(5.1991675),
            svbs: Some(7.6943475),
            capped_base_stock: Some(5.19198),
        },
        source: "literature",
    },
    LostSalesReferenceInstance {
        name: "lit_poisson_p4_l10",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::Poisson,
            demand_rate: 5.0,
            demand_lambda_low: 0.0,
            demand_lambda_high: 0.0,
            demand_p00: 0.0,
            demand_p11: 0.0,
        },
        lead_time: 10,
        holding_cost: 1.0,
        shortage_cost: 4.0,
        costs: HeuristicReferenceCosts {
            optimal: Some(5.31),
            myopic1: Some(5.8904),
            myopic2: Some(5.31),
            svbs: Some(8.03819),
            capped_base_stock: Some(5.27),
        },
        source: "literature+computed",
    },
    LostSalesReferenceInstance {
        name: "lit_poisson_p19_l4",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::Poisson,
            demand_rate: 5.0,
            demand_lambda_low: 0.0,
            demand_lambda_high: 0.0,
            demand_p00: 0.0,
            demand_p11: 0.0,
        },
        lead_time: 4,
        holding_cost: 1.0,
        shortage_cost: 19.0,
        costs: HeuristicReferenceCosts {
            optimal: Some(8.89),
            myopic1: Some(9.17321125),
            myopic2: Some(8.95289875),
            svbs: Some(9.56453125),
            capped_base_stock: Some(8.95),
        },
        source: "literature",
    },
    LostSalesReferenceInstance {
        name: "lit_poisson_p19_l6",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::Poisson,
            demand_rate: 5.0,
            demand_lambda_low: 0.0,
            demand_lambda_high: 0.0,
            demand_p00: 0.0,
            demand_p11: 0.0,
        },
        lead_time: 6,
        holding_cost: 1.0,
        shortage_cost: 19.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(10.26865),
            myopic2: Some(9.8306675),
            svbs: Some(11.23402),
            capped_base_stock: Some(9.8),
        },
        source: "literature",
    },
    LostSalesReferenceInstance {
        name: "lit_poisson_p19_l8",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::Poisson,
            demand_rate: 5.0,
            demand_lambda_low: 0.0,
            demand_lambda_high: 0.0,
            demand_p00: 0.0,
            demand_p11: 0.0,
        },
        lead_time: 8,
        holding_cost: 1.0,
        shortage_cost: 19.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(11.0916),
            myopic2: Some(10.510595),
            svbs: Some(12.3333375),
            capped_base_stock: Some(10.33341375),
        },
        source: "literature",
    },
    LostSalesReferenceInstance {
        name: "lit_poisson_p19_l10",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::Poisson,
            demand_rate: 5.0,
            demand_lambda_low: 0.0,
            demand_lambda_high: 0.0,
            demand_p00: 0.0,
            demand_p11: 0.0,
        },
        lead_time: 10,
        holding_cost: 1.0,
        shortage_cost: 19.0,
        costs: HeuristicReferenceCosts {
            optimal: Some(11.09),
            myopic1: Some(11.81955),
            myopic2: Some(11.09),
            svbs: Some(13.3359),
            capped_base_stock: Some(10.66),
        },
        source: "literature+computed",
    },
    LostSalesReferenceInstance {
        name: "lit_geometric_p4_l4",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::Geometric,
            demand_rate: 5.0,
            demand_lambda_low: 0.0,
            demand_lambda_high: 0.0,
            demand_p00: 0.0,
            demand_p11: 0.0,
        },
        lead_time: 4,
        holding_cost: 1.0,
        shortage_cost: 4.0,
        costs: HeuristicReferenceCosts {
            optimal: Some(10.61),
            myopic1: Some(11.21665),
            myopic2: Some(10.8),
            svbs: Some(13.72767),
            capped_base_stock: Some(10.7),
        },
        source: "literature+computed",
    },
    LostSalesReferenceInstance {
        name: "lit_geometric_p4_l6",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::Geometric,
            demand_rate: 5.0,
            demand_lambda_low: 0.0,
            demand_lambda_high: 0.0,
            demand_p00: 0.0,
            demand_p11: 0.0,
        },
        lead_time: 6,
        holding_cost: 1.0,
        shortage_cost: 4.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(11.65033),
            myopic2: Some(11.08),
            svbs: Some(15.73756),
            capped_base_stock: Some(10.91),
        },
        source: "literature+computed",
    },
    LostSalesReferenceInstance {
        name: "lit_geometric_p4_l8",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::Geometric,
            demand_rate: 5.0,
            demand_lambda_low: 0.0,
            demand_lambda_high: 0.0,
            demand_p00: 0.0,
            demand_p11: 0.0,
        },
        lead_time: 8,
        holding_cost: 1.0,
        shortage_cost: 4.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(11.92396),
            myopic2: Some(11.27),
            svbs: Some(17.63211),
            capped_base_stock: Some(10.96),
        },
        source: "literature+computed",
    },
    LostSalesReferenceInstance {
        name: "lit_geometric_p4_l10",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::Geometric,
            demand_rate: 5.0,
            demand_lambda_low: 0.0,
            demand_lambda_high: 0.0,
            demand_p00: 0.0,
            demand_p11: 0.0,
        },
        lead_time: 10,
        holding_cost: 1.0,
        shortage_cost: 4.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(12.07501),
            myopic2: Some(11.4),
            svbs: Some(19.42106),
            capped_base_stock: Some(10.98),
        },
        source: "literature+computed",
    },
    LostSalesReferenceInstance {
        name: "lit_geometric_p19_l4",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::Geometric,
            demand_rate: 5.0,
            demand_lambda_low: 0.0,
            demand_lambda_high: 0.0,
            demand_p00: 0.0,
            demand_p11: 0.0,
        },
        lead_time: 4,
        holding_cost: 1.0,
        shortage_cost: 19.0,
        costs: HeuristicReferenceCosts {
            optimal: Some(22.95),
            myopic1: Some(23.83598),
            myopic2: Some(23.28),
            svbs: Some(26.42911),
            capped_base_stock: Some(23.29),
        },
        source: "literature+computed",
    },
    LostSalesReferenceInstance {
        name: "lit_geometric_p19_l6",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::Geometric,
            demand_rate: 5.0,
            demand_lambda_low: 0.0,
            demand_lambda_high: 0.0,
            demand_p00: 0.0,
            demand_p11: 0.0,
        },
        lead_time: 6,
        holding_cost: 1.0,
        shortage_cost: 19.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(25.82144),
            myopic2: Some(24.93),
            svbs: Some(30.10294),
            capped_base_stock: Some(24.49),
        },
        source: "literature+computed",
    },
    LostSalesReferenceInstance {
        name: "lit_geometric_p19_l8",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::Geometric,
            demand_rate: 5.0,
            demand_lambda_low: 0.0,
            demand_lambda_high: 0.0,
            demand_p00: 0.0,
            demand_p11: 0.0,
        },
        lead_time: 8,
        holding_cost: 1.0,
        shortage_cost: 19.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(27.4068),
            myopic2: Some(26.21),
            svbs: Some(33.00846),
            capped_base_stock: Some(25.38),
        },
        source: "literature+computed",
    },
    LostSalesReferenceInstance {
        name: "lit_geometric_p19_l10",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::Geometric,
            demand_rate: 5.0,
            demand_lambda_low: 0.0,
            demand_lambda_high: 0.0,
            demand_p00: 0.0,
            demand_p11: 0.0,
        },
        lead_time: 10,
        holding_cost: 1.0,
        shortage_cost: 19.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(28.6719),
            myopic2: Some(27.27),
            svbs: Some(35.7609),
            capped_base_stock: Some(25.98),
        },
        source: "literature+computed",
    },
    LostSalesReferenceInstance {
        name: "lit_mmpp2_pos_p4_l4",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::MarkovModulatedPoisson2,
            demand_rate: 5.0,
            demand_lambda_low: 3.0,
            demand_lambda_high: 7.0,
            demand_p00: 0.9,
            demand_p11: 0.9,
        },
        lead_time: 4,
        holding_cost: 1.0,
        shortage_cost: 4.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(9.82251),
            myopic2: Some(9.4518),
            svbs: Some(10.3119),
            capped_base_stock: None,
        },
        source: "computed",
    },
    LostSalesReferenceInstance {
        name: "lit_mmpp2_pos_p4_l6",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::MarkovModulatedPoisson2,
            demand_rate: 5.0,
            demand_lambda_low: 3.0,
            demand_lambda_high: 7.0,
            demand_p00: 0.9,
            demand_p11: 0.9,
        },
        lead_time: 6,
        holding_cost: 1.0,
        shortage_cost: 4.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(11.18892),
            myopic2: Some(10.59106),
            svbs: Some(12.27057),
            capped_base_stock: None,
        },
        source: "computed",
    },
    LostSalesReferenceInstance {
        name: "lit_mmpp2_pos_p4_l8",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::MarkovModulatedPoisson2,
            demand_rate: 5.0,
            demand_lambda_low: 3.0,
            demand_lambda_high: 7.0,
            demand_p00: 0.9,
            demand_p11: 0.9,
        },
        lead_time: 8,
        holding_cost: 1.0,
        shortage_cost: 4.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(12.2556),
            myopic2: Some(11.45981),
            svbs: Some(13.99468),
            capped_base_stock: None,
        },
        source: "computed",
    },
    LostSalesReferenceInstance {
        name: "lit_mmpp2_pos_p4_l10",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::MarkovModulatedPoisson2,
            demand_rate: 5.0,
            demand_lambda_low: 3.0,
            demand_lambda_high: 7.0,
            demand_p00: 0.9,
            demand_p11: 0.9,
        },
        lead_time: 10,
        holding_cost: 1.0,
        shortage_cost: 4.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(13.13616),
            myopic2: Some(12.15503),
            svbs: Some(15.18972),
            capped_base_stock: None,
        },
        source: "computed",
    },
    LostSalesReferenceInstance {
        name: "lit_mmpp2_pos_p19_l4",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::MarkovModulatedPoisson2,
            demand_rate: 5.0,
            demand_lambda_low: 3.0,
            demand_lambda_high: 7.0,
            demand_p00: 0.9,
            demand_p11: 0.9,
        },
        lead_time: 4,
        holding_cost: 1.0,
        shortage_cost: 19.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(17.18234),
            myopic2: Some(17.64396),
            svbs: Some(16.53088),
            capped_base_stock: None,
        },
        source: "computed",
    },
    LostSalesReferenceInstance {
        name: "lit_mmpp2_pos_p19_l6",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::MarkovModulatedPoisson2,
            demand_rate: 5.0,
            demand_lambda_low: 3.0,
            demand_lambda_high: 7.0,
            demand_p00: 0.9,
            demand_p11: 0.9,
        },
        lead_time: 6,
        holding_cost: 1.0,
        shortage_cost: 19.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(20.12851),
            myopic2: Some(20.47379),
            svbs: Some(19.67724),
            capped_base_stock: None,
        },
        source: "computed",
    },
    LostSalesReferenceInstance {
        name: "lit_mmpp2_pos_p19_l8",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::MarkovModulatedPoisson2,
            demand_rate: 5.0,
            demand_lambda_low: 3.0,
            demand_lambda_high: 7.0,
            demand_p00: 0.9,
            demand_p11: 0.9,
        },
        lead_time: 8,
        holding_cost: 1.0,
        shortage_cost: 19.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(22.39949),
            myopic2: Some(22.55211),
            svbs: Some(22.17331),
            capped_base_stock: None,
        },
        source: "computed",
    },
    LostSalesReferenceInstance {
        name: "lit_mmpp2_pos_p19_l10",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::MarkovModulatedPoisson2,
            demand_rate: 5.0,
            demand_lambda_low: 3.0,
            demand_lambda_high: 7.0,
            demand_p00: 0.9,
            demand_p11: 0.9,
        },
        lead_time: 10,
        holding_cost: 1.0,
        shortage_cost: 19.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(24.21785),
            myopic2: Some(23.91256),
            svbs: Some(24.4575),
            capped_base_stock: None,
        },
        source: "computed",
    },
    LostSalesReferenceInstance {
        name: "lit_mmpp2_neg_p4_l4",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::MarkovModulatedPoisson2,
            demand_rate: 5.0,
            demand_lambda_low: 3.0,
            demand_lambda_high: 7.0,
            demand_p00: 0.1,
            demand_p11: 0.1,
        },
        lead_time: 4,
        holding_cost: 1.0,
        shortage_cost: 4.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(5.71978),
            myopic2: Some(5.41258),
            svbs: Some(7.32118),
            capped_base_stock: None,
        },
        source: "computed",
    },
    LostSalesReferenceInstance {
        name: "lit_mmpp2_neg_p4_l6",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::MarkovModulatedPoisson2,
            demand_rate: 5.0,
            demand_lambda_low: 3.0,
            demand_lambda_high: 7.0,
            demand_p00: 0.1,
            demand_p11: 0.1,
        },
        lead_time: 6,
        holding_cost: 1.0,
        shortage_cost: 4.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(5.9521),
            myopic2: Some(5.53321),
            svbs: Some(8.32912),
            capped_base_stock: None,
        },
        source: "computed",
    },
    LostSalesReferenceInstance {
        name: "lit_mmpp2_neg_p4_l8",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::MarkovModulatedPoisson2,
            demand_rate: 5.0,
            demand_lambda_low: 3.0,
            demand_lambda_high: 7.0,
            demand_p00: 0.1,
            demand_p11: 0.1,
        },
        lead_time: 8,
        holding_cost: 1.0,
        shortage_cost: 4.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(6.12425),
            myopic2: Some(5.61425),
            svbs: Some(9.31077),
            capped_base_stock: None,
        },
        source: "computed",
    },
    LostSalesReferenceInstance {
        name: "lit_mmpp2_neg_p4_l10",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::MarkovModulatedPoisson2,
            demand_rate: 5.0,
            demand_lambda_low: 3.0,
            demand_lambda_high: 7.0,
            demand_p00: 0.1,
            demand_p11: 0.1,
        },
        lead_time: 10,
        holding_cost: 1.0,
        shortage_cost: 4.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(6.21895),
            myopic2: Some(5.66218),
            svbs: Some(9.72266),
            capped_base_stock: None,
        },
        source: "computed",
    },
    LostSalesReferenceInstance {
        name: "lit_mmpp2_neg_p19_l4",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::MarkovModulatedPoisson2,
            demand_rate: 5.0,
            demand_lambda_low: 3.0,
            demand_lambda_high: 7.0,
            demand_p00: 0.1,
            demand_p11: 0.1,
        },
        lead_time: 4,
        holding_cost: 1.0,
        shortage_cost: 19.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(11.1214),
            myopic2: Some(10.43945),
            svbs: Some(12.55566),
            capped_base_stock: None,
        },
        source: "computed",
    },
    LostSalesReferenceInstance {
        name: "lit_mmpp2_neg_p19_l6",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::MarkovModulatedPoisson2,
            demand_rate: 5.0,
            demand_lambda_low: 3.0,
            demand_lambda_high: 7.0,
            demand_p00: 0.1,
            demand_p11: 0.1,
        },
        lead_time: 6,
        holding_cost: 1.0,
        shortage_cost: 19.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(12.39806),
            myopic2: Some(11.42936),
            svbs: Some(14.52729),
            capped_base_stock: None,
        },
        source: "computed",
    },
    LostSalesReferenceInstance {
        name: "lit_mmpp2_neg_p19_l8",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::MarkovModulatedPoisson2,
            demand_rate: 5.0,
            demand_lambda_low: 3.0,
            demand_lambda_high: 7.0,
            demand_p00: 0.1,
            demand_p11: 0.1,
        },
        lead_time: 8,
        holding_cost: 1.0,
        shortage_cost: 19.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(13.4002),
            myopic2: Some(12.17473),
            svbs: Some(15.65965),
            capped_base_stock: None,
        },
        source: "computed",
    },
    LostSalesReferenceInstance {
        name: "lit_mmpp2_neg_p19_l10",
        demand: LostSalesDemandConfig {
            kind: LostSalesDemandKind::MarkovModulatedPoisson2,
            demand_rate: 5.0,
            demand_lambda_low: 3.0,
            demand_lambda_high: 7.0,
            demand_p00: 0.1,
            demand_p11: 0.1,
        },
        lead_time: 10,
        holding_cost: 1.0,
        shortage_cost: 19.0,
        costs: HeuristicReferenceCosts {
            optimal: None,
            myopic1: Some(14.23462),
            myopic2: Some(12.78489),
            svbs: Some(17.51676),
            capped_base_stock: None,
        },
        source: "computed",
    },
];

/// Look up a reference instance by name.
pub fn reference_instance(name: &str) -> Option<&'static LostSalesReferenceInstance> {
    REFERENCE_INSTANCES.iter().find(|inst| inst.name == name)
}

/// All reference-instance names.
pub fn reference_instance_names() -> Vec<&'static str> {
    REFERENCE_INSTANCES.iter().map(|inst| inst.name).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vanilla_matches_literature() {
        let v = reference_instance("vanilla_l4_p4_poisson5").unwrap();
        assert_eq!(v.costs.myopic2, Some(4.82));
        assert_eq!(v.costs.svbs, Some(5.83));
    }

    #[test]
    fn every_grid_instance_has_the_three_heuristics() {
        // Myopic-1, Myopic-2, SVBS are populated (literature or computed) for
        // every instance on the active L in {4,6,8,10} grid.
        for inst in REFERENCE_INSTANCES {
            assert!(inst.costs.myopic1.is_some(), "{} missing myopic1", inst.name);
            assert!(inst.costs.myopic2.is_some(), "{} missing myopic2", inst.name);
            assert!(inst.costs.svbs.is_some(), "{} missing svbs", inst.name);
        }
    }
}

