#![allow(dead_code)]

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct PublishedBenchmarkReference {
    pub source: &'static str,
    pub url: &'static str,
    pub benchmark_policies: &'static [&'static str],
    pub notes: &'static str,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct VendorManagedInventoryReferenceInstance {
    pub name: &'static str,
    pub source: &'static str,
    pub url: &'static str,
    pub periods: usize,
    pub demand_distribution_kind: &'static str,
    pub demand_mean: f64,
    pub initial_dc_on_hand: usize,
    pub initial_retailer_on_hand: usize,
    pub initial_retailer_pipeline: usize,
    pub dc_replenishment_quantity: usize,
    pub dc_capacity: usize,
    pub shipment_cost_per_unit: f64,
    pub dc_holding_cost_per_unit: f64,
    pub retailer_holding_cost_per_unit: f64,
    pub stockout_cost_per_unit: f64,
    pub salvage_value_per_unit: f64,
    pub max_shipment_quantity: usize,
    pub benchmark_retailer_base_stock_level: usize,
    pub benchmark_dc_reserve_base_stock_level: usize,
    pub benchmark_dc_reserve_quantity: usize,
    pub notes: &'static str,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct WorkedTransitionReference {
    pub source: &'static str,
    pub url: &'static str,
    pub initial_dc_on_hand: usize,
    pub initial_retailer_on_hand: usize,
    pub initial_retailer_pipeline: usize,
    pub shipment_quantity: usize,
    pub realized_demand: usize,
    pub dc_replenishment_quantity: usize,
    pub dc_capacity: usize,
    pub shipment_cost_per_unit: f64,
    pub dc_holding_cost_per_unit: f64,
    pub retailer_holding_cost_per_unit: f64,
    pub stockout_cost_per_unit: f64,
    pub expected_arrivals_to_retailer: usize,
    pub expected_sales: usize,
    pub expected_lost_sales: usize,
    pub expected_dc_replenishment: usize,
    pub expected_next_dc_on_hand: usize,
    pub expected_next_retailer_on_hand: usize,
    pub expected_next_retailer_pipeline: usize,
    pub expected_period_cost: f64,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ExactVerificationReference {
    pub source: &'static str,
    pub url: &'static str,
    pub periods: usize,
    pub discount_factor: f64,
    pub initial_dc_on_hand: usize,
    pub initial_retailer_on_hand: usize,
    pub initial_retailer_pipeline: usize,
    pub dc_replenishment_quantity: usize,
    pub dc_capacity: usize,
    pub shipment_cost_per_unit: f64,
    pub dc_holding_cost_per_unit: f64,
    pub retailer_holding_cost_per_unit: f64,
    pub stockout_cost_per_unit: f64,
    pub salvage_value_per_unit: f64,
    pub demand_support: &'static [u32],
    pub demand_probabilities: &'static [f64],
    pub max_shipment_quantity: usize,
    pub retailer_base_stock_level: usize,
    pub dc_reserve_base_stock_level: usize,
    pub dc_reserve_quantity: usize,
    pub notes: &'static str,
}

pub const GIANNOCCARO_2010_REFERENCE: PublishedBenchmarkReference = PublishedBenchmarkReference {
    source: "Giannoccaro and Pontrandolfo (2010), A Reinforcement Learning Approach for Inventory Replenishment in Vendor-Managed Inventory Systems With Consignment Inventory",
    url: "https://doi.org/10.1080/10429247.2010.11431878",
    benchmark_policies: &["retailer_base_stock", "projected_order_up_to", "rl_policy"],
    notes: "The paper studies replenishment decisions in a vendor-managed inventory system with consignment stock. The repo interpretation keeps the vendor-controlled retailer replenishment decision, explicit DC and retailer stock, and stochastic retailer demand while stripping away multi-retailer and richer contract details.",
};

pub const PRIMARY_REFERENCE_INSTANCE: VendorManagedInventoryReferenceInstance =
    VendorManagedInventoryReferenceInstance {
        name: "giannoccaro2010_style_single_retailer",
        source: GIANNOCCARO_2010_REFERENCE.source,
        url: GIANNOCCARO_2010_REFERENCE.url,
        periods: 24,
        demand_distribution_kind: "poisson",
        demand_mean: 2.5,
        initial_dc_on_hand: 8,
        initial_retailer_on_hand: 2,
        initial_retailer_pipeline: 1,
        dc_replenishment_quantity: 3,
        dc_capacity: 10,
        shipment_cost_per_unit: 0.4,
        dc_holding_cost_per_unit: 0.25,
        retailer_holding_cost_per_unit: 0.6,
        stockout_cost_per_unit: 5.0,
        salvage_value_per_unit: 0.2,
        max_shipment_quantity: 5,
        benchmark_retailer_base_stock_level: 4,
        benchmark_dc_reserve_base_stock_level: 5,
        benchmark_dc_reserve_quantity: 2,
        notes: "Canonical repo interpretation of vendor-managed inventory: a supplier DC chooses shipments into one retailer's consignment stock under a one-period transport lead time, deterministic upstream replenishment at the DC, and retailer lost-sales demand.",
    };

pub const WORKED_TRANSITION_REFERENCE: WorkedTransitionReference = WorkedTransitionReference {
    source: GIANNOCCARO_2010_REFERENCE.source,
    url: GIANNOCCARO_2010_REFERENCE.url,
    initial_dc_on_hand: 4,
    initial_retailer_on_hand: 1,
    initial_retailer_pipeline: 1,
    shipment_quantity: 2,
    realized_demand: 3,
    dc_replenishment_quantity: 2,
    dc_capacity: 5,
    shipment_cost_per_unit: 0.4,
    dc_holding_cost_per_unit: 0.3,
    retailer_holding_cost_per_unit: 0.6,
    stockout_cost_per_unit: 4.0,
    expected_arrivals_to_retailer: 1,
    expected_sales: 2,
    expected_lost_sales: 1,
    expected_dc_replenishment: 2,
    expected_next_dc_on_hand: 4,
    expected_next_retailer_on_hand: 0,
    expected_next_retailer_pipeline: 2,
    expected_period_cost: 6.0,
};

pub const VERIFICATION_PROBLEM_INSTANCE: ExactVerificationReference = ExactVerificationReference {
    source: GIANNOCCARO_2010_REFERENCE.source,
    url: GIANNOCCARO_2010_REFERENCE.url,
    periods: 5,
    discount_factor: 0.99,
    initial_dc_on_hand: 4,
    initial_retailer_on_hand: 1,
    initial_retailer_pipeline: 1,
    dc_replenishment_quantity: 2,
    dc_capacity: 5,
    shipment_cost_per_unit: 0.4,
    dc_holding_cost_per_unit: 0.3,
    retailer_holding_cost_per_unit: 0.6,
    stockout_cost_per_unit: 4.0,
    salvage_value_per_unit: 0.2,
    demand_support: &[0, 1, 2, 3],
    demand_probabilities: &[0.15, 0.35, 0.3, 0.2],
    max_shipment_quantity: 4,
    retailer_base_stock_level: 3,
    dc_reserve_base_stock_level: 4,
    dc_reserve_quantity: 1,
    notes: "Repo-native exact verifier on a reduced single-retailer VMI instance with a small discrete demand support. It preserves the DC stock constraint, one-period shipment pipeline, and vendor-controlled replenishment action while keeping the finite-horizon DP small enough for exact regression tests.",
};
