use crate::problems::joint_replenishment::demand::DemandRange;

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct PublishedBenchmarkReference {
    pub source: &'static str,
    pub url: &'static str,
    pub benchmark_policies: &'static [&'static str],
    pub reported_numbers_available: bool,
    pub numbers_anchor_repo_assertions: bool,
    pub notes: &'static str,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct JointReplenishmentReferenceInstance {
    pub name: &'static str,
    pub source: &'static str,
    pub url: &'static str,
    pub num_items: usize,
    pub truck_capacity: usize,
    pub major_order_cost: f64,
    pub minor_order_costs: &'static [f64],
    pub holding_costs: &'static [f64],
    pub shortage_costs: &'static [f64],
    pub demand_ranges: &'static [DemandRange],
    pub notes: &'static str,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct WorkedTransitionReference {
    pub source: &'static str,
    pub url: &'static str,
    pub initial_inventory_levels: &'static [i32],
    pub action: &'static [usize],
    pub realized_demands: &'static [usize],
    pub truck_capacity: usize,
    pub major_order_cost: f64,
    pub minor_order_costs: &'static [f64],
    pub holding_costs: &'static [f64],
    pub shortage_costs: &'static [f64],
    pub expected_next_inventory_levels: &'static [i32],
    pub expected_trucks_used: usize,
    pub expected_order_cost: f64,
    pub expected_holding_cost: f64,
    pub expected_shortage_cost: f64,
    pub expected_period_cost: f64,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ExactVerificationReference {
    pub source: &'static str,
    pub url: &'static str,
    pub literature_verified: bool,
    pub verification_source: &'static str,
    pub periods: usize,
    pub discount_factor: f64,
    pub truck_capacity: usize,
    pub max_order_quantities: &'static [usize],
    pub initial_inventory_levels: &'static [i32],
    pub major_order_cost: f64,
    pub minor_order_costs: &'static [f64],
    pub holding_costs: &'static [f64],
    pub shortage_costs: &'static [f64],
    pub demand_ranges: &'static [DemandRange],
    pub moq_item_targets: &'static [usize],
    pub moq_review_period: usize,
    pub moq_rounding_threshold: f64,
    pub dynout_item_targets: &'static [usize],
    pub notes: &'static str,
}

pub const VANVUCHELEN_2020_REFERENCE: PublishedBenchmarkReference = PublishedBenchmarkReference {
    source: "Vanvuchelen et al. (2020), Computers in Industry 122, 103300",
    url: "https://merit.url.edu/ws/portalfiles/portal/42792438/Use_of_Proximal_Policy_Optimization.pdf",
    benchmark_policies: &["ppo", "(Q,S|T)_moq", "dyn-out"],
    reported_numbers_available: true,
    numbers_anchor_repo_assertions: false,
    notes: "The public PDF exposes all 16 small-scale setting definitions in Table 2 and relative optimality-gap figures for PPO, MOQ, and DYN-OUT. It does not provide exact per-setting benchmark rows suitable for repo assertions.",
};

pub const SMALL_SCALE_DEMAND_RANGES_A: &[DemandRange] = &[
    DemandRange { low: 0, high: 5 },
    DemandRange { low: 0, high: 3 },
];

pub const SMALL_SCALE_DEMAND_RANGES_B: &[DemandRange] = &[
    DemandRange { low: 0, high: 6 },
    DemandRange { low: 0, high: 2 },
];

pub const SMALL_SCALE_MINOR_COSTS_A: &[f64] = &[10.0, 10.0];
pub const SMALL_SCALE_MINOR_COSTS_B: &[f64] = &[40.0, 10.0];

pub const SMALL_SCALE_SETTINGS: [JointReplenishmentReferenceInstance; 16] = [
    JointReplenishmentReferenceInstance {
        name: "vanvuchelen2020_small_scale_setting_1",
        source: VANVUCHELEN_2020_REFERENCE.source,
        url: VANVUCHELEN_2020_REFERENCE.url,
        num_items: 2,
        truck_capacity: 6,
        major_order_cost: 75.0,
        minor_order_costs: SMALL_SCALE_MINOR_COSTS_A,
        holding_costs: &[1.0, 1.0],
        shortage_costs: &[19.0, 19.0],
        demand_ranges: SMALL_SCALE_DEMAND_RANGES_A,
        notes: "Table 2 setting 1: low-low holding costs, symmetric minor ordering costs, and demand pair U[0,5] / U[0,3].",
    },
    JointReplenishmentReferenceInstance {
        name: "vanvuchelen2020_small_scale_setting_2",
        source: VANVUCHELEN_2020_REFERENCE.source,
        url: VANVUCHELEN_2020_REFERENCE.url,
        num_items: 2,
        truck_capacity: 6,
        major_order_cost: 75.0,
        minor_order_costs: SMALL_SCALE_MINOR_COSTS_A,
        holding_costs: &[1.0, 5.0],
        shortage_costs: &[19.0, 95.0],
        demand_ranges: SMALL_SCALE_DEMAND_RANGES_A,
        notes: "Table 2 setting 2: low-high holding costs, symmetric minor ordering costs, and demand pair U[0,5] / U[0,3].",
    },
    JointReplenishmentReferenceInstance {
        name: "vanvuchelen2020_small_scale_setting_3",
        source: VANVUCHELEN_2020_REFERENCE.source,
        url: VANVUCHELEN_2020_REFERENCE.url,
        num_items: 2,
        truck_capacity: 6,
        major_order_cost: 75.0,
        minor_order_costs: SMALL_SCALE_MINOR_COSTS_A,
        holding_costs: &[5.0, 1.0],
        shortage_costs: &[95.0, 19.0],
        demand_ranges: SMALL_SCALE_DEMAND_RANGES_A,
        notes: "Table 2 setting 3: high-low holding costs, symmetric minor ordering costs, and demand pair U[0,5] / U[0,3].",
    },
    JointReplenishmentReferenceInstance {
        name: "vanvuchelen2020_small_scale_setting_4",
        source: VANVUCHELEN_2020_REFERENCE.source,
        url: VANVUCHELEN_2020_REFERENCE.url,
        num_items: 2,
        truck_capacity: 6,
        major_order_cost: 75.0,
        minor_order_costs: SMALL_SCALE_MINOR_COSTS_A,
        holding_costs: &[5.0, 5.0],
        shortage_costs: &[95.0, 95.0],
        demand_ranges: SMALL_SCALE_DEMAND_RANGES_A,
        notes: "Table 2 setting 4: high-high holding costs, symmetric minor ordering costs, and demand pair U[0,5] / U[0,3].",
    },
    JointReplenishmentReferenceInstance {
        name: "vanvuchelen2020_small_scale_setting_5",
        source: VANVUCHELEN_2020_REFERENCE.source,
        url: VANVUCHELEN_2020_REFERENCE.url,
        num_items: 2,
        truck_capacity: 6,
        major_order_cost: 75.0,
        minor_order_costs: SMALL_SCALE_MINOR_COSTS_B,
        holding_costs: &[1.0, 1.0],
        shortage_costs: &[19.0, 19.0],
        demand_ranges: SMALL_SCALE_DEMAND_RANGES_A,
        notes: "Table 2 setting 5: low-low holding costs, asymmetric minor ordering costs, and demand pair U[0,5] / U[0,3]. Figure 3 and Figure 4 focus on this family.",
    },
    JointReplenishmentReferenceInstance {
        name: "vanvuchelen2020_small_scale_setting_6",
        source: VANVUCHELEN_2020_REFERENCE.source,
        url: VANVUCHELEN_2020_REFERENCE.url,
        num_items: 2,
        truck_capacity: 6,
        major_order_cost: 75.0,
        minor_order_costs: SMALL_SCALE_MINOR_COSTS_B,
        holding_costs: &[1.0, 5.0],
        shortage_costs: &[19.0, 95.0],
        demand_ranges: SMALL_SCALE_DEMAND_RANGES_A,
        notes: "Table 2 setting 6: low-high holding costs, asymmetric minor ordering costs, and demand pair U[0,5] / U[0,3].",
    },
    JointReplenishmentReferenceInstance {
        name: "vanvuchelen2020_small_scale_setting_7",
        source: VANVUCHELEN_2020_REFERENCE.source,
        url: VANVUCHELEN_2020_REFERENCE.url,
        num_items: 2,
        truck_capacity: 6,
        major_order_cost: 75.0,
        minor_order_costs: SMALL_SCALE_MINOR_COSTS_B,
        holding_costs: &[5.0, 1.0],
        shortage_costs: &[95.0, 19.0],
        demand_ranges: SMALL_SCALE_DEMAND_RANGES_A,
        notes: "Table 2 setting 7: high-low holding costs, asymmetric minor ordering costs, and demand pair U[0,5] / U[0,3].",
    },
    JointReplenishmentReferenceInstance {
        name: "vanvuchelen2020_small_scale_setting_8",
        source: VANVUCHELEN_2020_REFERENCE.source,
        url: VANVUCHELEN_2020_REFERENCE.url,
        num_items: 2,
        truck_capacity: 6,
        major_order_cost: 75.0,
        minor_order_costs: SMALL_SCALE_MINOR_COSTS_B,
        holding_costs: &[5.0, 5.0],
        shortage_costs: &[95.0, 95.0],
        demand_ranges: SMALL_SCALE_DEMAND_RANGES_A,
        notes: "Table 2 setting 8: high-high holding costs, asymmetric minor ordering costs, and demand pair U[0,5] / U[0,3].",
    },
    JointReplenishmentReferenceInstance {
        name: "vanvuchelen2020_small_scale_setting_9",
        source: VANVUCHELEN_2020_REFERENCE.source,
        url: VANVUCHELEN_2020_REFERENCE.url,
        num_items: 2,
        truck_capacity: 6,
        major_order_cost: 75.0,
        minor_order_costs: SMALL_SCALE_MINOR_COSTS_A,
        holding_costs: &[1.0, 1.0],
        shortage_costs: &[19.0, 19.0],
        demand_ranges: SMALL_SCALE_DEMAND_RANGES_B,
        notes: "Table 2 setting 9: low-low holding costs, symmetric minor ordering costs, and demand pair U[0,6] / U[0,2].",
    },
    JointReplenishmentReferenceInstance {
        name: "vanvuchelen2020_small_scale_setting_10",
        source: VANVUCHELEN_2020_REFERENCE.source,
        url: VANVUCHELEN_2020_REFERENCE.url,
        num_items: 2,
        truck_capacity: 6,
        major_order_cost: 75.0,
        minor_order_costs: SMALL_SCALE_MINOR_COSTS_A,
        holding_costs: &[1.0, 5.0],
        shortage_costs: &[19.0, 95.0],
        demand_ranges: SMALL_SCALE_DEMAND_RANGES_B,
        notes: "Table 2 setting 10: low-high holding costs, symmetric minor ordering costs, and demand pair U[0,6] / U[0,2].",
    },
    JointReplenishmentReferenceInstance {
        name: "vanvuchelen2020_small_scale_setting_11",
        source: VANVUCHELEN_2020_REFERENCE.source,
        url: VANVUCHELEN_2020_REFERENCE.url,
        num_items: 2,
        truck_capacity: 6,
        major_order_cost: 75.0,
        minor_order_costs: SMALL_SCALE_MINOR_COSTS_A,
        holding_costs: &[5.0, 1.0],
        shortage_costs: &[95.0, 19.0],
        demand_ranges: SMALL_SCALE_DEMAND_RANGES_B,
        notes: "Table 2 setting 11: high-low holding costs, symmetric minor ordering costs, and demand pair U[0,6] / U[0,2].",
    },
    JointReplenishmentReferenceInstance {
        name: "vanvuchelen2020_small_scale_setting_12",
        source: VANVUCHELEN_2020_REFERENCE.source,
        url: VANVUCHELEN_2020_REFERENCE.url,
        num_items: 2,
        truck_capacity: 6,
        major_order_cost: 75.0,
        minor_order_costs: SMALL_SCALE_MINOR_COSTS_A,
        holding_costs: &[5.0, 5.0],
        shortage_costs: &[95.0, 95.0],
        demand_ranges: SMALL_SCALE_DEMAND_RANGES_B,
        notes: "Table 2 setting 12: high-high holding costs, symmetric minor ordering costs, and demand pair U[0,6] / U[0,2].",
    },
    JointReplenishmentReferenceInstance {
        name: "vanvuchelen2020_small_scale_setting_13",
        source: VANVUCHELEN_2020_REFERENCE.source,
        url: VANVUCHELEN_2020_REFERENCE.url,
        num_items: 2,
        truck_capacity: 6,
        major_order_cost: 75.0,
        minor_order_costs: SMALL_SCALE_MINOR_COSTS_B,
        holding_costs: &[1.0, 1.0],
        shortage_costs: &[19.0, 19.0],
        demand_ranges: SMALL_SCALE_DEMAND_RANGES_B,
        notes: "Table 2 setting 13: low-low holding costs, asymmetric minor ordering costs, and demand pair U[0,6] / U[0,2].",
    },
    JointReplenishmentReferenceInstance {
        name: "vanvuchelen2020_small_scale_setting_14",
        source: VANVUCHELEN_2020_REFERENCE.source,
        url: VANVUCHELEN_2020_REFERENCE.url,
        num_items: 2,
        truck_capacity: 6,
        major_order_cost: 75.0,
        minor_order_costs: SMALL_SCALE_MINOR_COSTS_B,
        holding_costs: &[1.0, 5.0],
        shortage_costs: &[19.0, 95.0],
        demand_ranges: SMALL_SCALE_DEMAND_RANGES_B,
        notes: "Table 2 setting 14: low-high holding costs, asymmetric minor ordering costs, and demand pair U[0,6] / U[0,2].",
    },
    JointReplenishmentReferenceInstance {
        name: "vanvuchelen2020_small_scale_setting_15",
        source: VANVUCHELEN_2020_REFERENCE.source,
        url: VANVUCHELEN_2020_REFERENCE.url,
        num_items: 2,
        truck_capacity: 6,
        major_order_cost: 75.0,
        minor_order_costs: SMALL_SCALE_MINOR_COSTS_B,
        holding_costs: &[5.0, 1.0],
        shortage_costs: &[95.0, 19.0],
        demand_ranges: SMALL_SCALE_DEMAND_RANGES_B,
        notes: "Table 2 setting 15: high-low holding costs, asymmetric minor ordering costs, and demand pair U[0,6] / U[0,2].",
    },
    JointReplenishmentReferenceInstance {
        name: "vanvuchelen2020_small_scale_setting_16",
        source: VANVUCHELEN_2020_REFERENCE.source,
        url: VANVUCHELEN_2020_REFERENCE.url,
        num_items: 2,
        truck_capacity: 6,
        major_order_cost: 75.0,
        minor_order_costs: SMALL_SCALE_MINOR_COSTS_B,
        holding_costs: &[5.0, 5.0],
        shortage_costs: &[95.0, 95.0],
        demand_ranges: SMALL_SCALE_DEMAND_RANGES_B,
        notes: "Table 2 setting 16: high-high holding costs, asymmetric minor ordering costs, and demand pair U[0,6] / U[0,2].",
    },
];

pub const PRIMARY_REFERENCE_INSTANCE: JointReplenishmentReferenceInstance = SMALL_SCALE_SETTINGS[4];

pub const WORKED_TRANSITION_REFERENCE: WorkedTransitionReference = WorkedTransitionReference {
    source: VANVUCHELEN_2020_REFERENCE.source,
    url: VANVUCHELEN_2020_REFERENCE.url,
    initial_inventory_levels: &[1, -2],
    action: &[4, 1],
    realized_demands: &[3, 0],
    truck_capacity: 6,
    major_order_cost: 75.0,
    minor_order_costs: SMALL_SCALE_MINOR_COSTS_A,
    holding_costs: &[1.0, 1.0],
    shortage_costs: &[19.0, 19.0],
    expected_next_inventory_levels: &[2, -1],
    expected_trucks_used: 1,
    expected_order_cost: 95.0,
    expected_holding_cost: 2.0,
    expected_shortage_cost: 19.0,
    expected_period_cost: 116.0,
};

pub const VERIFICATION_PROBLEM_INSTANCE: ExactVerificationReference = ExactVerificationReference {
    source: VANVUCHELEN_2020_REFERENCE.source,
    url: VANVUCHELEN_2020_REFERENCE.url,
    literature_verified: false,
    verification_source: "repo_exact_solver_not_verified_against_literature",
    periods: 4,
    discount_factor: 0.99,
    truck_capacity: 6,
    max_order_quantities: &[12, 12],
    initial_inventory_levels: &[2, 0],
    major_order_cost: 75.0,
    minor_order_costs: SMALL_SCALE_MINOR_COSTS_A,
    holding_costs: &[1.0, 1.0],
    shortage_costs: &[19.0, 19.0],
    demand_ranges: SMALL_SCALE_DEMAND_RANGES_A,
    moq_item_targets: &[8, 5],
    moq_review_period: 1,
    moq_rounding_threshold: 2.0,
    dynout_item_targets: &[8, 5],
    notes: "Finite-horizon repo-native exact verifier built on the paper's small-scale setting 1 model family. The public paper gives the setting parameters but not exact benchmark rows for repo assertions, so the reduced verifier stores only the problem instance and generates exact values at verification time.",
};
