#[derive(Clone, Copy, Debug, PartialEq)]
pub struct PublishedBenchmarkReference {
    pub source: &'static str,
    pub url: &'static str,
    pub benchmark_policies: &'static [&'static str],
    pub notes: &'static str,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SparePartsReferenceInstance {
    pub name: &'static str,
    pub source: &'static str,
    pub url: &'static str,
    pub installed_base: usize,
    pub procurement_lead_time: usize,
    pub repair_lead_time: usize,
    pub initial_on_hand_inventory: usize,
    pub initial_backlog: usize,
    pub initial_procurement_pipeline: &'static [usize],
    pub initial_repair_pipeline: &'static [usize],
    pub failure_probability: f64,
    pub holding_cost: f64,
    pub downtime_cost: f64,
    pub procurement_cost: f64,
    pub benchmark_base_stock_level: usize,
    pub benchmark_lead_time_mean_cover_safety_buffer: f64,
    pub notes: &'static str,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct WorkedTransitionReference {
    pub source: &'static str,
    pub url: &'static str,
    pub installed_base: usize,
    pub initial_on_hand_inventory: usize,
    pub initial_backlog: usize,
    pub initial_procurement_pipeline: &'static [usize],
    pub initial_repair_pipeline: &'static [usize],
    pub action: usize,
    pub realized_failures: usize,
    pub holding_cost: f64,
    pub downtime_cost: f64,
    pub procurement_cost: f64,
    pub expected_procurement_arrival: usize,
    pub expected_repair_return: usize,
    pub expected_post_failure_on_hand_inventory: usize,
    pub expected_post_failure_backlog: usize,
    pub expected_next_on_hand_inventory: usize,
    pub expected_next_backlog: usize,
    pub expected_next_procurement_pipeline: &'static [usize],
    pub expected_next_repair_pipeline: &'static [usize],
    pub expected_period_cost: f64,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ExactVerificationReference {
    pub source: &'static str,
    pub url: &'static str,
    pub periods: usize,
    pub discount_factor: f64,
    pub installed_base: usize,
    pub procurement_lead_time: usize,
    pub repair_lead_time: usize,
    pub initial_on_hand_inventory: usize,
    pub initial_backlog: usize,
    pub initial_procurement_pipeline: &'static [usize],
    pub initial_repair_pipeline: &'static [usize],
    pub failure_probability: f64,
    pub holding_cost: f64,
    pub downtime_cost: f64,
    pub procurement_cost: f64,
    pub max_order_quantity: usize,
    pub base_stock_level: usize,
    pub lead_time_mean_cover_safety_buffer: f64,
    pub expected_optimal_discounted_cost: f64,
    pub expected_optimal_first_action: usize,
    pub expected_base_stock_discounted_cost: f64,
    pub expected_base_stock_first_action: usize,
    pub expected_lead_time_mean_cover_discounted_cost: f64,
    pub expected_lead_time_mean_cover_first_action: usize,
    pub notes: &'static str,
}

pub const SPARE_PARTS_REVIEW_REFERENCE: PublishedBenchmarkReference = PublishedBenchmarkReference {
    source: "Spare Parts Inventory Management: A Literature Review (2021), Sustainability 13(5), 2460",
    url: "https://www.mdpi.com/2071-1050/13/5/2460",
    benchmark_policies: &["base_stock", "one_for_one_replenishment", "multi-echelon transshipment"],
    notes: "The review highlights that spare-parts systems are often single-echelon, repairable, and continuous-review. It explicitly notes that one-for-one replenishment or base-stock control is widely used for repairable spare parts.",
};

pub const ZHOU_2024_REFERENCE: PublishedBenchmarkReference = PublishedBenchmarkReference {
    source: "Zhou et al. (2024), Applied Mathematical Modelling 125(B), 827-844",
    url: "https://doi.org/10.1016/j.apm.2023.10.039",
    benchmark_policies: &["marl", "multi-echelon spare-parts baselines"],
    notes: "This paper motivates spare_parts_inventory as a distinct RL family through a multi-echelon spare-parts setting with recent multi-agent DRL results.",
};

pub const VAN_DER_HAAR_2025_REFERENCE: PublishedBenchmarkReference = PublishedBenchmarkReference {
    source: "van der Haar et al. (2025), Industrializing Deep Reinforcement Learning for Operational Spare Parts Inventory Management",
    url: "https://ssrn.com/abstract=4999374",
    benchmark_policies: &["drl", "distance-based transshipment and expediting heuristics"],
    notes: "The paper shows that large-scale operational spare-parts management relies on proactive transshipments and expediting, which motivates keeping spare_parts_inventory separate from general network_inventory.",
};

pub const PRIMARY_REFERENCE_INSTANCE: SparePartsReferenceInstance = SparePartsReferenceInstance {
    name: "single_echelon_repairable_operational_spares",
    source: SPARE_PARTS_REVIEW_REFERENCE.source,
    url: SPARE_PARTS_REVIEW_REFERENCE.url,
    installed_base: 12,
    procurement_lead_time: 3,
    repair_lead_time: 2,
    initial_on_hand_inventory: 2,
    initial_backlog: 0,
    initial_procurement_pipeline: &[0, 0, 0],
    initial_repair_pipeline: &[1, 0],
    failure_probability: 0.08,
    holding_cost: 0.25,
    downtime_cost: 20.0,
    procurement_cost: 3.0,
    benchmark_base_stock_level: 5,
    benchmark_lead_time_mean_cover_safety_buffer: 1.0,
    notes: "Canonical repo interpretation of spare parts as a single-echelon repairable service-parts problem with deterministic repair returns and explicit procurement to grow the rotable pool.",
};

pub const WORKED_TRANSITION_REFERENCE: WorkedTransitionReference = WorkedTransitionReference {
    source: PRIMARY_REFERENCE_INSTANCE.source,
    url: PRIMARY_REFERENCE_INSTANCE.url,
    installed_base: 3,
    initial_on_hand_inventory: 1,
    initial_backlog: 1,
    initial_procurement_pipeline: &[1, 0],
    initial_repair_pipeline: &[0, 2],
    action: 2,
    realized_failures: 1,
    holding_cost: 0.5,
    downtime_cost: 6.0,
    procurement_cost: 2.0,
    expected_procurement_arrival: 1,
    expected_repair_return: 0,
    expected_post_failure_on_hand_inventory: 0,
    expected_post_failure_backlog: 1,
    expected_next_on_hand_inventory: 0,
    expected_next_backlog: 0,
    expected_next_procurement_pipeline: &[0, 2],
    expected_next_repair_pipeline: &[2, 1],
    expected_period_cost: 10.0,
};

pub const VERIFICATION_PROBLEM_INSTANCE: ExactVerificationReference = ExactVerificationReference {
    source: SPARE_PARTS_REVIEW_REFERENCE.source,
    url: SPARE_PARTS_REVIEW_REFERENCE.url,
    periods: 4,
    discount_factor: 0.99,
    installed_base: 3,
    procurement_lead_time: 2,
    repair_lead_time: 2,
    initial_on_hand_inventory: 1,
    initial_backlog: 0,
    initial_procurement_pipeline: &[0, 0],
    initial_repair_pipeline: &[0, 0],
    failure_probability: 0.4,
    holding_cost: 0.5,
    downtime_cost: 6.0,
    procurement_cost: 2.0,
    max_order_quantity: 4,
    base_stock_level: 3,
    lead_time_mean_cover_safety_buffer: 1.0,
    expected_optimal_discounted_cost: 28.39366298236964,
    expected_optimal_first_action: 2,
    expected_base_stock_discounted_cost: 28.39366298236964,
    expected_base_stock_first_action: 2,
    expected_lead_time_mean_cover_discounted_cost: 28.91224647176473,
    expected_lead_time_mean_cover_first_action: 3,
    notes: "Repo-native exact verifier on a reduced repairable spare-parts instance. The state is small enough for routine finite-horizon DP while preserving installed-base failures, repair returns, and procurement decisions.",
};
