pub mod references;

pub use references::{
    ExactVerificationReference, LiteratureBenchmarkFamily, RandomYieldReferenceInstance,
    CHEN_2018_REFERENCE, INDERFURTH_2015_POSITIVE_LEAD_TIMES,
    INDERFURTH_2015_PROPORTIONAL_YIELD_PAIRS, INDERFURTH_2015_REFERENCE,
    LITERATURE_BENCHMARK_FAMILIES, PRIMARY_REFERENCE_INSTANCE, VERIFICATION_PROBLEM_INSTANCE,
    YAN_2026_REFERENCE,
};
