#[derive(Clone, Copy, Debug, PartialEq)]
pub struct HormuzPriceScenarioPreset {
    pub scenario_id: &'static str,
    pub label: &'static str,
    pub description: &'static str,
    pub closure_fraction_day_0: f64,
    pub closure_fraction_day_n: f64,
    pub bypass_utilization: f64,
    pub strategic_reserve_release_million_bpd: f64,
    pub floating_storage_release_million_bpd: f64,
    pub additional_non_hormuz_supply_response_million_bpd: f64,
    pub inventory_buffer_draw_million_bpd: f64,
    pub upstream_shut_in_share_of_uncovered_loss: f64,
    pub persistent_risk_premium_usd_per_bbl: f64,
    pub mean_reversion_to_target: f64,
    pub daily_volatility_usd_per_bbl: f64,
}

pub const MONTH_AHEAD_SCENARIO_PRESETS: &[HormuzPriceScenarioPreset] = &[
    HormuzPriceScenarioPreset {
        scenario_id: "de_escalation_and_gradual_reopening",
        label: "De-escalation and gradual reopening",
        description: "Traffic remains disrupted in early April but transit progressively normalizes and coordinated buffers absorb most of the lost flow.",
        closure_fraction_day_0: 0.20,
        closure_fraction_day_n: 0.05,
        bypass_utilization: 0.90,
        strategic_reserve_release_million_bpd: 0.50,
        floating_storage_release_million_bpd: 0.40,
        additional_non_hormuz_supply_response_million_bpd: 0.25,
        inventory_buffer_draw_million_bpd: 0.90,
        upstream_shut_in_share_of_uncovered_loss: 0.08,
        persistent_risk_premium_usd_per_bbl: 4.0,
        mean_reversion_to_target: 0.10,
        daily_volatility_usd_per_bbl: 1.8,
    },
    HormuzPriceScenarioPreset {
        scenario_id: "managed_partial_disruption",
        label: "Managed partial disruption",
        description: "Hormuz throughput is materially constrained for a month, but Saudi and UAE bypass capacity plus reserve releases cap the net shortage.",
        closure_fraction_day_0: 0.40,
        closure_fraction_day_n: 0.25,
        bypass_utilization: 0.90,
        strategic_reserve_release_million_bpd: 0.90,
        floating_storage_release_million_bpd: 0.50,
        additional_non_hormuz_supply_response_million_bpd: 0.35,
        inventory_buffer_draw_million_bpd: 0.70,
        upstream_shut_in_share_of_uncovered_loss: 0.10,
        persistent_risk_premium_usd_per_bbl: 8.0,
        mean_reversion_to_target: 0.09,
        daily_volatility_usd_per_bbl: 2.0,
    },
    HormuzPriceScenarioPreset {
        scenario_id: "severe_partial_disruption",
        label: "Severe partial disruption",
        description: "A large share of Hormuz throughput stays offline, with meaningful upstream shut-ins and only partial mitigation from rerouting and reserves.",
        closure_fraction_day_0: 0.70,
        closure_fraction_day_n: 0.50,
        bypass_utilization: 0.95,
        strategic_reserve_release_million_bpd: 1.40,
        floating_storage_release_million_bpd: 0.70,
        additional_non_hormuz_supply_response_million_bpd: 0.45,
        inventory_buffer_draw_million_bpd: 0.80,
        upstream_shut_in_share_of_uncovered_loss: 0.18,
        persistent_risk_premium_usd_per_bbl: 16.0,
        mean_reversion_to_target: 0.09,
        daily_volatility_usd_per_bbl: 2.4,
    },
    HormuzPriceScenarioPreset {
        scenario_id: "full_closure_coordinated_response",
        label: "Full closure with coordinated response",
        description: "The strait is effectively closed, but alternative export routes, reserve releases, and emergency coordination partially cushion the market.",
        closure_fraction_day_0: 1.00,
        closure_fraction_day_n: 0.85,
        bypass_utilization: 1.00,
        strategic_reserve_release_million_bpd: 2.50,
        floating_storage_release_million_bpd: 1.50,
        additional_non_hormuz_supply_response_million_bpd: 0.55,
        inventory_buffer_draw_million_bpd: 1.40,
        upstream_shut_in_share_of_uncovered_loss: 0.20,
        persistent_risk_premium_usd_per_bbl: 22.0,
        mean_reversion_to_target: 0.08,
        daily_volatility_usd_per_bbl: 2.8,
    },
    HormuzPriceScenarioPreset {
        scenario_id: "full_closure_limited_response",
        label: "Full closure with limited response",
        description: "The strait is closed for the whole month and policy mitigation is weak, leaving a large net supply shock and elevated geopolitical risk premium.",
        closure_fraction_day_0: 1.00,
        closure_fraction_day_n: 1.00,
        bypass_utilization: 0.70,
        strategic_reserve_release_million_bpd: 0.80,
        floating_storage_release_million_bpd: 0.40,
        additional_non_hormuz_supply_response_million_bpd: 0.15,
        inventory_buffer_draw_million_bpd: 0.40,
        upstream_shut_in_share_of_uncovered_loss: 0.28,
        persistent_risk_premium_usd_per_bbl: 35.0,
        mean_reversion_to_target: 0.08,
        daily_volatility_usd_per_bbl: 3.2,
    },
];

pub fn month_ahead_scenario_presets() -> &'static [HormuzPriceScenarioPreset] {
    MONTH_AHEAD_SCENARIO_PRESETS
}
